version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=virdi
      - DOCKER_INFLUXDB_INIT_BUCKET=virdi_metrics
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=super_secret_token
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    restart: unless-stopped

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    volumes:
      - chronograf-storage:/var/lib/chronograf
    restart: unless-stopped

  virdi:
    build: .
    container_name: virdi
    ports:
      - "50051:50051"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=super_secret_token
      - INFLUXDB_ORG=virdi
      - INFLUXDB_BUCKET=virdi_metrics
    restart: unless-stopped

volumes:
  influxdb-data:
  influxdb-config:
  chronograf-storage:
