# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.grpc_service.proto.virdi_pb2 as virdi__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in virdi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VirdiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OfferProduction = channel.unary_stream(
                '/Virdi/OfferProduction',
                request_serializer=virdi__pb2.ProductionOffer.SerializeToString,
                response_deserializer=virdi__pb2.ProductionRequest.FromString,
                _registered_method=True)
        self.Produce = channel.stream_unary(
                '/Virdi/Produce',
                request_serializer=virdi__pb2.ResourceProduction.SerializeToString,
                response_deserializer=virdi__pb2.ProductionResponse.FromString,
                _registered_method=True)


class VirdiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OfferProduction(self, request, context):
        """Client offers a resource
        Server registers the client as a possible producer of the resource
        Sent by the client when first creating a producer for a resource / connecting to the server
        The server sends a message whenever it needs the resource
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Produce(self, request_iterator, context):
        """Client streams a resource until the server cancels
        The server requests this using the ProductionRequest stream in OfferProduction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VirdiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OfferProduction': grpc.unary_stream_rpc_method_handler(
                    servicer.OfferProduction,
                    request_deserializer=virdi__pb2.ProductionOffer.FromString,
                    response_serializer=virdi__pb2.ProductionRequest.SerializeToString,
            ),
            'Produce': grpc.stream_unary_rpc_method_handler(
                    servicer.Produce,
                    request_deserializer=virdi__pb2.ResourceProduction.FromString,
                    response_serializer=virdi__pb2.ProductionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Virdi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Virdi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Virdi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OfferProduction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Virdi/OfferProduction',
            virdi__pb2.ProductionOffer.SerializeToString,
            virdi__pb2.ProductionRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Produce(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Virdi/Produce',
            virdi__pb2.ResourceProduction.SerializeToString,
            virdi__pb2.ProductionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
